application:
  subdomain: miniboard
  background_task: true
  multi_instance: false
  upstreams:
    - location: /
      backend: http://miniboard.cloud.lazycat.app.miniboard.lzcapp:8849/
services:
  miniboard:
    # upstream: aceberg/miniboard:1.2.2
    image: docker.1ms.run/aceberg/miniboard:1.2.2
    environment:
      - TZ=Asia/beijing
      - HOST=0.0.0.0
      - PORT=8849
      - THEME=flatly
      - COLOR=dark
    binds:
      - /lzcapp/var/miniboard:/data/miniboard
    setup_script: |
      if [ -z "$(find /data/miniboard/board.yaml -mindepth 1 -maxdepth 1)" ]; then
          cp  /lzcapp/pkg/content/board.yaml  /lzcapp/var/miniboard/
      fi
